apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-operator
  namespace: terra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: terraform-operator
  namespace: terra
rules:
- apiGroups: ["terra.core.nubes.ru"]
  resources: ["providerreleases", "providerreleases/status"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terraform-operator
  namespace: terra
subjects:
- kind: ServiceAccount
  name: terraform-operator
  namespace: terra
roleRef:
  kind: Role
  name: terraform-operator
  apiGroup: rbac.authorization.k8s.io
